<?php

namespace ContainerRHLD6vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PkQocCNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PkQocCN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PkQocCN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apiTokenRepository' => ['privates', 'App\\Repository\\ApiTokenRepository', 'getApiTokenRepositoryService', true],
            'profileUpdateService' => ['services', 'App\\Service\\ProfileUpdateService', 'getProfileUpdateServiceService', true],
        ], [
            'apiTokenRepository' => 'App\\Repository\\ApiTokenRepository',
            'profileUpdateService' => 'App\\Service\\ProfileUpdateService',
        ]);
    }
}
