<?php

namespace ContainerRHLD6vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BepkdcCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bepkdcC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bepkdcC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'generatedArticlesRepository' => ['privates', 'App\\Repository\\GeneratedArticlesRepository', 'getGeneratedArticlesRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'generatedArticlesRepository' => 'App\\Repository\\GeneratedArticlesRepository',
            'paginator' => '?',
        ]);
    }
}
