<?php

namespace ContainerRHLD6vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MS3YlFWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mS3YlFW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mS3YlFW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleGeneratorService' => ['privates', 'App\\Service\\ArticleGeneratorService', 'getArticleGeneratorServiceService', true],
            'subscriptionService' => ['privates', 'App\\Service\\SubscriptionService', 'getSubscriptionServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'articleGeneratorService' => 'App\\Service\\ArticleGeneratorService',
            'subscriptionService' => 'App\\Service\\SubscriptionService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
