<?php

namespace ContainerRHLD6vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleGeneratorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ArticleGeneratorController' shared autowired service.
     *
     * @return \App\Controller\ArticleGeneratorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ArticleGeneratorController.php';

        $container->services['App\\Controller\\ArticleGeneratorController'] = $instance = new \App\Controller\ArticleGeneratorController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\ArticleGeneratorController', $container));

        return $instance;
    }
}
