<?php

namespace ContainerRHLD6vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T2oWGTn.App\Entity\ApiToken' shared service.
     *
     * @return \App\Entity\ApiToken
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T2oWGTn": it needs an instance of "App\\Entity\\ApiToken" but this type has been excluded in "config/services.yaml".');
    }
}
