<?php

namespace ContainerRHLD6vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMorphExtensionRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Runtime\MorphExtensionRuntime' shared autowired service.
     *
     * @return \App\Twig\Runtime\MorphExtensionRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Runtime/MorphExtensionRuntime.php';

        return $container->privates['App\\Twig\\Runtime\\MorphExtensionRuntime'] = new \App\Twig\Runtime\MorphExtensionRuntime();
    }
}
