<?php

namespace ContainerRHLD6vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplatedEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YM3n3ub.Symfony\Bridge\Twig\Mime\TemplatedEmail' shared service.
     *
     * @return \Symfony\Bridge\Twig\Mime\TemplatedEmail
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YM3n3ub": it references class "Symfony\\Bridge\\Twig\\Mime\\TemplatedEmail" but no such service exists.');
    }
}
