<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YM3n3ubService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YM3n3ub' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YM3n3ub'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'email' => ['privates', '.errored..service_locator.YM3n3ub.Symfony\\Bridge\\Twig\\Mime\\TemplatedEmail', NULL, 'Cannot autowire service ".service_locator.YM3n3ub": it references class "Symfony\\Bridge\\Twig\\Mime\\TemplatedEmail" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.YM3n3ub.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.YM3n3ub": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'email' => 'Symfony\\Bridge\\Twig\\Mime\\TemplatedEmail',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
