<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T2oWGTnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T2oWGTn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T2oWGTn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apiToken' => ['privates', '.errored..service_locator.T2oWGTn.App\\Entity\\ApiToken', NULL, 'Cannot autowire service ".service_locator.T2oWGTn": it needs an instance of "App\\Entity\\ApiToken" but this type has been excluded in "config/services.yaml".'],
            'emailVerifier' => ['services', 'App\\Security\\EmailVerifier', 'getEmailVerifierService', true],
            'form' => ['privates', '.errored..service_locator.T2oWGTn.Symfony\\Component\\Form\\FormInterface', NULL, 'Cannot autowire service ".service_locator.T2oWGTn": it references interface "Symfony\\Component\\Form\\FormInterface" but no such service exists. Did you create a class that implements this interface?'],
            'user' => ['privates', '.errored..service_locator.T2oWGTn.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.T2oWGTn": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'apiToken' => 'App\\Entity\\ApiToken',
            'emailVerifier' => 'App\\Security\\EmailVerifier',
            'form' => 'Symfony\\Component\\Form\\FormInterface',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
