<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GRZ13NPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gRZ13NP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gRZ13NP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'emailVerifier' => ['services', 'App\\Security\\EmailVerifier', 'getEmailVerifierService', true],
            'profileUpdateService' => ['services', 'App\\Service\\ProfileUpdateService', 'getProfileUpdateServiceService', true],
            'registrationService' => ['services', 'App\\Service\\RegistrationService', 'getRegistrationServiceService', true],
        ], [
            'emailVerifier' => 'App\\Security\\EmailVerifier',
            'profileUpdateService' => 'App\\Service\\ProfileUpdateService',
            'registrationService' => 'App\\Service\\RegistrationService',
        ]);
    }
}
