<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OcEt16xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OcEt16x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OcEt16x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'generatedArticlesRepository' => ['privates', 'App\\Repository\\GeneratedArticlesRepository', 'getGeneratedArticlesRepositoryService', true],
            'subscriptionService' => ['privates', 'App\\Service\\SubscriptionService', 'getSubscriptionServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'generatedArticlesRepository' => 'App\\Repository\\GeneratedArticlesRepository',
            'subscriptionService' => 'App\\Service\\SubscriptionService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
