<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2wJV_YkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2wJV.yk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2wJV.yk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'moduleService' => ['privates', 'App\\Service\\ModuleService', 'getModuleServiceService', true],
        ], [
            'moduleService' => 'App\\Service\\ModuleService',
        ]);
    }
}
