<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6CMNLRTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6CMNLRT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6CMNLRT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleGeneratorService' => ['privates', 'App\\Service\\ArticleGeneratorService', 'getArticleGeneratorServiceService', true],
            'unregisteredUsersRepository' => ['privates', 'App\\Repository\\UnregisteredUsersRepository', 'getUnregisteredUsersRepositoryService', true],
            'unregisteredUsersService' => ['privates', 'App\\Service\\UnregisteredUsersService', 'getUnregisteredUsersServiceService', true],
        ], [
            'articleGeneratorService' => 'App\\Service\\ArticleGeneratorService',
            'unregisteredUsersRepository' => 'App\\Repository\\UnregisteredUsersRepository',
            'unregisteredUsersService' => 'App\\Service\\UnregisteredUsersService',
        ]);
    }
}
