<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RTdTNr_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RTdTNr.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RTdTNr.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apiTokenRepository' => ['privates', 'App\\Repository\\ApiTokenRepository', 'getApiTokenRepositoryService', true],
        ], [
            'apiTokenRepository' => 'App\\Repository\\ApiTokenRepository',
        ]);
    }
}
