<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zw7rCwlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zw7rCwl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zw7rCwl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiArticleGeneratorController::index' => ['privates', '.service_locator.QkHY7fE', 'get_ServiceLocator_QkHY7fEService', true],
            'App\\Controller\\ArticleGeneratorController::input' => ['privates', '.service_locator.mS3YlFW', 'get_ServiceLocator_MS3YlFWService', true],
            'App\\Controller\\DashboardController::articleDetail' => ['privates', '.service_locator.CYp4YuS', 'get_ServiceLocator_CYp4YuSService', true],
            'App\\Controller\\DashboardController::articlesHistory' => ['privates', '.service_locator.bepkdcC', 'get_ServiceLocator_BepkdcCService', true],
            'App\\Controller\\DashboardController::dashboard' => ['privates', '.service_locator.OcEt16x', 'get_ServiceLocator_OcEt16xService', true],
            'App\\Controller\\DashboardController::templateAdd' => ['privates', '.service_locator.2wJV.yk', 'get_ServiceLocator_2wJV_YkService', true],
            'App\\Controller\\DashboardController::templateDelete' => ['privates', '.service_locator.BsfINrE', 'get_ServiceLocator_BsfINrEService', true],
            'App\\Controller\\DashboardController::templates' => ['privates', '.service_locator.cbasXva', 'get_ServiceLocator_CbasXvaService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\MainController::try' => ['privates', '.service_locator.6CMNLRT', 'get_ServiceLocator_6CMNLRTService', true],
            'App\\Controller\\ProfileController::profile' => ['privates', '.service_locator.RTdTNr.', 'get_ServiceLocator_RTdTNr_Service', true],
            'App\\Controller\\ProfileController::profileUpdate' => ['privates', '.service_locator._9GNO0N', 'get_ServiceLocator_9GNO0NService', true],
            'App\\Controller\\ProfileController::verifyEmailChange' => ['privates', '.service_locator.PkQocCN', 'get_ServiceLocator_PkQocCNService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.gRZ13NP', 'get_ServiceLocator_GRZ13NPService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.WqpXNEt', 'get_ServiceLocator_WqpXNEtService', true],
            'App\\Controller\\SubscriptionController::orderSubscription' => ['privates', '.service_locator.9UD.N6C', 'get_ServiceLocator_9UD_N6CService', true],
            'App\\Controller\\SubscriptionController::subscription' => ['privates', '.service_locator.W.yz9dg', 'get_ServiceLocator_W_Yz9dgService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Security\\EmailVerifier::changeUserEmail' => ['privates', '.service_locator.YM3n3ub', 'get_ServiceLocator_YM3n3ubService', true],
            'App\\Security\\EmailVerifier::handleEmailConfirmation' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Security\\EmailVerifier::sendEmailConfirmation' => ['privates', '.service_locator.YM3n3ub', 'get_ServiceLocator_YM3n3ubService', true],
            'App\\Service\\ProfileUpdateService::updateProfile' => ['privates', '.service_locator.UwqMnSE', 'get_ServiceLocator_UwqMnSEService', true],
            'App\\Service\\RegistrationService::register' => ['privates', '.service_locator.T2oWGTn', 'get_ServiceLocator_T2oWGTnService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ApiArticleGeneratorController:index' => ['privates', '.service_locator.QkHY7fE', 'get_ServiceLocator_QkHY7fEService', true],
            'App\\Controller\\ArticleGeneratorController:input' => ['privates', '.service_locator.mS3YlFW', 'get_ServiceLocator_MS3YlFWService', true],
            'App\\Controller\\DashboardController:articleDetail' => ['privates', '.service_locator.CYp4YuS', 'get_ServiceLocator_CYp4YuSService', true],
            'App\\Controller\\DashboardController:articlesHistory' => ['privates', '.service_locator.bepkdcC', 'get_ServiceLocator_BepkdcCService', true],
            'App\\Controller\\DashboardController:dashboard' => ['privates', '.service_locator.OcEt16x', 'get_ServiceLocator_OcEt16xService', true],
            'App\\Controller\\DashboardController:templateAdd' => ['privates', '.service_locator.2wJV.yk', 'get_ServiceLocator_2wJV_YkService', true],
            'App\\Controller\\DashboardController:templateDelete' => ['privates', '.service_locator.BsfINrE', 'get_ServiceLocator_BsfINrEService', true],
            'App\\Controller\\DashboardController:templates' => ['privates', '.service_locator.cbasXva', 'get_ServiceLocator_CbasXvaService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\MainController:try' => ['privates', '.service_locator.6CMNLRT', 'get_ServiceLocator_6CMNLRTService', true],
            'App\\Controller\\ProfileController:profile' => ['privates', '.service_locator.RTdTNr.', 'get_ServiceLocator_RTdTNr_Service', true],
            'App\\Controller\\ProfileController:profileUpdate' => ['privates', '.service_locator._9GNO0N', 'get_ServiceLocator_9GNO0NService', true],
            'App\\Controller\\ProfileController:verifyEmailChange' => ['privates', '.service_locator.PkQocCN', 'get_ServiceLocator_PkQocCNService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.gRZ13NP', 'get_ServiceLocator_GRZ13NPService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.WqpXNEt', 'get_ServiceLocator_WqpXNEtService', true],
            'App\\Controller\\SubscriptionController:orderSubscription' => ['privates', '.service_locator.9UD.N6C', 'get_ServiceLocator_9UD_N6CService', true],
            'App\\Controller\\SubscriptionController:subscription' => ['privates', '.service_locator.W.yz9dg', 'get_ServiceLocator_W_Yz9dgService', true],
            'App\\Security\\EmailVerifier:changeUserEmail' => ['privates', '.service_locator.YM3n3ub', 'get_ServiceLocator_YM3n3ubService', true],
            'App\\Security\\EmailVerifier:handleEmailConfirmation' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Security\\EmailVerifier:sendEmailConfirmation' => ['privates', '.service_locator.YM3n3ub', 'get_ServiceLocator_YM3n3ubService', true],
            'App\\Service\\ProfileUpdateService:updateProfile' => ['privates', '.service_locator.UwqMnSE', 'get_ServiceLocator_UwqMnSEService', true],
            'App\\Service\\RegistrationService:register' => ['privates', '.service_locator.T2oWGTn', 'get_ServiceLocator_T2oWGTnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ApiArticleGeneratorController::index' => '?',
            'App\\Controller\\ArticleGeneratorController::input' => '?',
            'App\\Controller\\DashboardController::articleDetail' => '?',
            'App\\Controller\\DashboardController::articlesHistory' => '?',
            'App\\Controller\\DashboardController::dashboard' => '?',
            'App\\Controller\\DashboardController::templateAdd' => '?',
            'App\\Controller\\DashboardController::templateDelete' => '?',
            'App\\Controller\\DashboardController::templates' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\MainController::try' => '?',
            'App\\Controller\\ProfileController::profile' => '?',
            'App\\Controller\\ProfileController::profileUpdate' => '?',
            'App\\Controller\\ProfileController::verifyEmailChange' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SubscriptionController::orderSubscription' => '?',
            'App\\Controller\\SubscriptionController::subscription' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Security\\EmailVerifier::changeUserEmail' => '?',
            'App\\Security\\EmailVerifier::handleEmailConfirmation' => '?',
            'App\\Security\\EmailVerifier::sendEmailConfirmation' => '?',
            'App\\Service\\ProfileUpdateService::updateProfile' => '?',
            'App\\Service\\RegistrationService::register' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiArticleGeneratorController:index' => '?',
            'App\\Controller\\ArticleGeneratorController:input' => '?',
            'App\\Controller\\DashboardController:articleDetail' => '?',
            'App\\Controller\\DashboardController:articlesHistory' => '?',
            'App\\Controller\\DashboardController:dashboard' => '?',
            'App\\Controller\\DashboardController:templateAdd' => '?',
            'App\\Controller\\DashboardController:templateDelete' => '?',
            'App\\Controller\\DashboardController:templates' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\MainController:try' => '?',
            'App\\Controller\\ProfileController:profile' => '?',
            'App\\Controller\\ProfileController:profileUpdate' => '?',
            'App\\Controller\\ProfileController:verifyEmailChange' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SubscriptionController:orderSubscription' => '?',
            'App\\Controller\\SubscriptionController:subscription' => '?',
            'App\\Security\\EmailVerifier:changeUserEmail' => '?',
            'App\\Security\\EmailVerifier:handleEmailConfirmation' => '?',
            'App\\Security\\EmailVerifier:sendEmailConfirmation' => '?',
            'App\\Service\\ProfileUpdateService:updateProfile' => '?',
            'App\\Service\\RegistrationService:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
