<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CYp4YuSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CYp4YuS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CYp4YuS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleGeneratorService' => ['privates', 'App\\Service\\ArticleGeneratorService', 'getArticleGeneratorServiceService', true],
            'generatedArticlesRepository' => ['privates', 'App\\Repository\\GeneratedArticlesRepository', 'getGeneratedArticlesRepositoryService', true],
        ], [
            'articleGeneratorService' => 'App\\Service\\ArticleGeneratorService',
            'generatedArticlesRepository' => 'App\\Repository\\GeneratedArticlesRepository',
        ]);
    }
}
