<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W_Yz9dgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W.yz9dg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W.yz9dg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'subscriptionService' => ['privates', 'App\\Service\\SubscriptionService', 'getSubscriptionServiceService', true],
        ], [
            'subscriptionService' => 'App\\Service\\SubscriptionService',
        ]);
    }
}
