<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleGeneratorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ArticleGeneratorService' shared autowired service.
     *
     * @return \App\Service\ArticleGeneratorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ArticleGeneratorService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileUploader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $a = ($container->privates['App\\Service\\SubscriptionService'] ?? $container->load('getSubscriptionServiceService'));

        if (isset($container->privates['App\\Service\\ArticleGeneratorService'])) {
            return $container->privates['App\\Service\\ArticleGeneratorService'];
        }

        return $container->privates['App\\Service\\ArticleGeneratorService'] = new \App\Service\ArticleGeneratorService('/uploads/article_images/', ($container->privates['App\\Repository\\ArticleContentRepository'] ?? $container->load('getArticleContentRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\GeneratedArticlesRepository'] ?? $container->load('getGeneratedArticlesRepositoryService')), ($container->privates['App\\Service\\ModuleService'] ?? $container->load('getModuleServiceService')), ($container->privates['App\\Repository\\ModuleRepository'] ?? $container->load('getModuleRepositoryService')), new \App\Service\FileUploader((\dirname(__DIR__, 4).'/public/uploads/article_images'), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('ru'))), $a, ($container->privates['debug.validator'] ?? $container->getDebug_ValidatorService()), ($container->privates['App\\Repository\\ApiTokenRepository'] ?? $container->load('getApiTokenRepositoryService')));
    }
}
