<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleCreateTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ArticleCreateType' shared autowired service.
     *
     * @return \App\Form\ArticleCreateType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ArticleCreateType.php';

        $a = ($container->privates['App\\Service\\SubscriptionService'] ?? $container->load('getSubscriptionServiceService'));

        if (isset($container->privates['App\\Form\\ArticleCreateType'])) {
            return $container->privates['App\\Form\\ArticleCreateType'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Form\\ArticleCreateType'])) {
            return $container->privates['App\\Form\\ArticleCreateType'];
        }

        return $container->privates['App\\Form\\ArticleCreateType'] = new \App\Form\ArticleCreateType($a, ($container->privates['App\\Repository\\GeneratedArticlesRepository'] ?? $container->load('getGeneratedArticlesRepositoryService')), $b);
    }
}
