<?php

namespace ContainerD0qllqE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ModuleService' shared autowired service.
     *
     * @return \App\Service\ModuleService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ModuleService.php';

        return $container->privates['App\\Service\\ModuleService'] = new \App\Service\ModuleService(\dirname(__DIR__, 4), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
