<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRHLD6vr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRHLD6vr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRHLD6vr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRHLD6vr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRHLD6vr\App_KernelDevDebugContainer([
    'container.build_hash' => 'RHLD6vr',
    'container.build_id' => '68a5a792',
    'container.build_time' => 1706540531,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRHLD6vr');
